name: textlint

on:
  pull_request:
    # paths:
    # - "contents/**/*.md"
    # - "README.md"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  textlint-ja:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install textlint rules
        run: npm install textlint-rule-preset-ja-spacing

      - name: Run textlint
        run: textlint ./contents/**/*.md
